### ISSUE TITLE
Doesn't work without options

### ISSUE THREAD

**Issue by simonsmith** [davidtheclark/stylelint-selector-bem-pattern#10]
The source seems to imply that it will default to SUIT:

``` js
options = options || { preset: 'suit' };
```

However the plugin doesn't seem to even run unless I have at least the following:

``` js
module.exports = {
  plugins: ['stylelint-selector-bem-pattern'],
  rules: {
    'selector-bem-pattern': {}
  }
};
```

At which point `options` is set to `{}` and the default preset is never picked up. Is it correct that stylelint works this way and never calls a plugin unless you have some settings?

Cheers

**Comment by davidtheclark** [comment]
The convention for stylelint is definitely to *require an explicit expectation*. So do think it makes sense to expect someone to include `'selector-bem-pattern': { present: 'suit' }`. I didn't consider this actually when writing the plugin. Should probably 

- Remove the default option so that an error is thrown if no options are provided, or an empty object is.
- Add documentation clarifying this.

Sound good?

**Comment by simonsmith** [comment]
Yeah a doc update sounds a good addition. :+1:

**Comment by davidtheclark** [comment]
Docs are updated and code cleaned up in 0.2.2
